#!/bin/bash

if [ $# -eq 0 ]
then
    echo "=> Usage: fact [<path to test script>.clj|<path to directory>]"
    exit 1
fi

java -cp deps/clojure.jar:deps/clojure-contrib.jar clojure.lang.Script src/run-fato.clj -- $1